/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sam
 */
public class ventaInicio extends javax.swing.JFrame {

    private int idProfesor = 0;

    /**
     * Creates new form ventaInicio
     */
    public ventaInicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumno = new javax.swing.JButton();
        btnProfesor = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlumno.setBackground(new java.awt.Color(255, 102, 0));
        btnAlumno.setFont(new java.awt.Font("Roboto Lt", 1, 24)); // NOI18N
        btnAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogAlumno.png"))); // NOI18N
        btnAlumno.setText("Alumno");
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 250, 100));

        btnProfesor.setBackground(new java.awt.Color(0, 0, 102));
        btnProfesor.setFont(new java.awt.Font("Roboto Lt", 1, 24)); // NOI18N
        btnProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogProfesor.png"))); // NOI18N
        btnProfesor.setText("Profesor");
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 250, 100));

        lblDescripcion.setFont(new java.awt.Font("Roboto Lt", 1, 24)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 51));
        lblDescripcion.setText("Por favor selecciona como ingresar al sistema");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MultiMath.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Global.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAlumnoActionPerformed
        ventanaLoginAlumnos vLoginA = new ventanaLoginAlumnos();
        vLoginA.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnAlumnoActionPerformed

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnProfesorActionPerformed
        // Accediendo al siguiente frame con el boton
        ventanaLoginProfesor vLoginP = new ventanaLoginProfesor();
        vLoginP.setVisible(true);
        this.dispose();

    }// GEN-LAST:event_btnProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDescripcion;
    // End of variables declaration//GEN-END:variables
}
