/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexion.Conexion;
import java.net.URL;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author sam
 */
public class vOpcionesProfesor extends javax.swing.JFrame {

    /**
     * Creates new form vOpcionesProfesor
     */
    public vOpcionesProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Opciones del Profesor");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumnosRegistrados = new javax.swing.JButton();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlumnosRegistrados.setBackground(new java.awt.Color(255, 87, 51));
        btnAlumnosRegistrados.setFont(new java.awt.Font("Roboto Lt", 1, 24)); // NOI18N
        btnAlumnosRegistrados.setText("Alumnos Registrados");
        btnAlumnosRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosRegistradosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumnosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 310, 60));

        btnRegistrarAlumno.setBackground(new java.awt.Color(199, 0, 57));
        btnRegistrarAlumno.setFont(new java.awt.Font("Roboto Lt", 1, 24)); // NOI18N
        btnRegistrarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogCRUDE.png"))); // NOI18N
        btnRegistrarAlumno.setText("Registrar Alumno");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 310, 60));

        btnRegresar.setBackground(new java.awt.Color(102, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Roboto Lt", 1, 18)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reg.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Global.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        vCRUDEAlumnos crude = new vCRUDEAlumnos();
        crude.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnAlumnosRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosRegistradosActionPerformed
        //Generando reportes de tus alumnos:
        
        Conexion conexion = new Conexion();
        Connection connection = conexion.obtenerConexion();
        JasperReport reporte = null;

        URL path = this.getClass().getResource("/reportes/AlumnosRegistrados.jasper");
        try {
            reporte = (JasperReport) JRLoader.loadObject(path) ;
            
            //TODO: LLenar el reporte con algunos parametros y la conexion a bd
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, connection);
            
            //Generar vista del reporte 
            JasperViewer view = new JasperViewer(jprint, false);
            
            //Evitar Freezen molestos
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(vOpcionesProfesor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlumnosRegistradosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ventaInicio vInicio = new ventaInicio();
        vInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnosRegistrados;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
